### DISCUSSION TITLE
Can I build php-cgi executable with it?

### DISCUSSION THREAD

**Discussion by cztomczak** [crazywhalecc/static-php-cli#595] [General]
If I remove the `--disable-cgi` flag passed to configure script, would that be expected to work?
https://github.com/search?q=repo%3Acrazywhalecc%2Fstatic-php-cli%20cgi&type=code

**Comment by crazywhalecc** [comment]
No. CGI is another SAPI and we don't support currently. Although this is untested, you may be able to remove `--disable-cgi`, add `--enable-cgi` and modify the XXXBuilder source code for your OS (e.g. add a `buildCGI()` method) . But this may be a lot of work.

**Reply by Lea-Reift** [reply]
Hi. Can I ask what modifications explicitly I'd need to make in order to make a CGI SAPI work? I really need it for a project. Or in case you accept personalized requests, where do I get in touch?

**Reply by henderkes** [reply]
It should be very simple. ./configure with `--enable-cgi` and then copy the `buildCli()` method of LinuxBuilder (or MacOSBuilder) but rename Cli to Cgi in every occurence.

**Reply by Lea-Reift** [reply]
Why not the CLI builder method of windows?

**Reply by henderkes** [reply]
I mean if you are building on Windows, obviously?

**Reply by Lea-Reift** [reply]
Did that, the build is completed. I can see the modules with -m and the version with -v, but got a segmentation fault running the CGI with -b 127.0.0.1:9000. This is my craft file:
```yml
php-version: 8.4
extensions: bcmath,bz2,calendar,ctype,curl,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,libxml,mbstring,openssl,pdo,pdo_sqlite,phar,session,simplexml,soap,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib
sapi:
  - cgi
download-options:
  prefer-pre-built: true
```
