### ISSUE TITLE
Better build UX

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#702]
When I was modifying test-extensions.php today, I suddenly realized that the previous [simplified UX issue](https://github.com/crazywhalecc/static-php-cli/issues/187) seems to be solved by specifying a standard parameter input interface.

In other words, the parameters of the three build-related commands are expressed in the form of build-suite.yml or config.mak or other files, so that the desired results can be built with one command, and the command calls the build parameters internally. At the same time, it can also provide a direction for the future [setup-static-php](https://github.com/static-php/setup-static-php).

**Comment by crazywhalecc** [comment]
```yaml
# build-suite.yml
php-version: 8.4
extensions: bcmath,swoole,pcntl
libs: libavif,freetype
sapi: cli,micro
debug: true
build-options:
  with-suggested-libs: false
  with-suggested-exts: false
  build-shared: xdebug
  no-strip: false
  disable-opcache-jit: false
  with-config-file-path: ""
  with-config-file-scan-dir: ""
  with-hardcoded-ini: []
  with-micro-fake-cli: false
  with-added-patch: []
  without-micro-ext-test: false
  with-upx-pack: false
  with-micro-logo: ""
  enable-micro-win32: false
download-options:
  shallow-clone: false
  with-php: 8.4
```
