### ISSUE TITLE
CraftCommand does not forward build-options to build command

### ISSUE THREAD

**Issue by vworldat** [crazywhalecc/static-php-cli#732]
Given the following `craft.yml`:
```yaml
php-version: 8.4
extensions: "curl"
sapi: cli
build-options:
  with-clean: false
  prefer-pre-built: true
  with-config-file-path: /custom/config/path
```

I'd expect the following build process to be executed:
```sh
'/usr/local/bin/php' 'bin/spc' 'build' '--no-motd' 'curl' '--with-libs=' '--build-cli' '--with-suggested-libs' '--with-config-file-path="/custom/config/path"'
```

But the actual process looks like this:
```sh
'/usr/local/bin/php' 'bin/spc' 'build' '--no-motd' 'curl' '--with-libs=' '--build-cli'
```

I'll shortly push a fix.
