### ISSUE TITLE
imagick fails to load in spc-gnu-docker

### ISSUE THREAD

**Issue by henderkes** [crazywhalecc/static-php-cli#770]
```console
[root@138017c724d4 app]# /app/buildroot/bin/php -n -d "extension_dir=/app/buildroot/modules" -d "extension=imagick" --ri "imagick"

Warning: PHP Startup: Unable to load dynamic library 'imagick' (tried: /app/buildroot/modules/imagick (/app/buildroot/modules/imagick: cannot open shared object file: No such file or directory), /app/buildroot/modules/imagick.so (/app/buildroot/modules/imagick.so: undefined symbol: _ZTINSt6thread6_StateE)) in Unknown on line 0
Extension 'imagick' not present.
```

**Comment by henderkes** [comment]
looks like compiling imagick in the old docker images uses symbols of libstdc++ that aren't defined in the version of libstdc++ that is installed on the system

```console
[root@d4a31a3e4d2c app]# nm -D /lib64/libstdc++.so.6 | grep thread
000000000006a330 T _ZN9__gnu_cxx6__poolILb1EE16_M_get_thread_idEv@@GLIBCXX_3.4.4
000000000006a5b0 T _ZN9__gnu_cxx6__poolILb1EE21_M_destroy_thread_keyEPv@@GLIBCXX_3.4.4
00000000000b5170 T _ZNSt11this_thread11__sleep_forENSt6chrono8durationIlSt5ratioILl1ELl1EEEENS1_IlS2_ILl1ELl1000000000EEEE@@GLIBCXX_3.4.18
000000000007c410 T _ZNSt12__basic_fileIcEC1EP15pthread_mutex_t@@GLIBCXX_3.4
000000000007c410 T _ZNSt12__basic_fileIcEC2EP15pthread_mutex_t@@GLIBCXX_3.4
00000000000b53f0 T _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEE@@GLIBCXX_3.4.11
00000000000b5150 T _ZNSt6thread20hardware_concurrencyEv@@GLIBCXX_3.4.17
00000000000b50d0 T _ZNSt6thread4joinEv@@GLIBCXX_3.4.11
00000000000b5110 T _ZNSt6thread6detachEv@@GLIBCXX_3.4.11
000000000005ced0 T __cxa_thread_atexit@@CXXABI_1.3.7
                 w __pthread_key_create
                 w pthread_cond_broadcast@@GLIBC_2.3.2
                 w pthread_cond_destroy@@GLIBC_2.3.2
                 w pthread_cond_signal@@GLIBC_2.3.2
                 w pthread_cond_wait@@GLIBC_2.3.2
                 w pthread_create
                 w pthread_detach
                 w pthread_getspecific
                 w pthread_join
                 w pthread_key_create
                 w pthread_key_delete
                 w pthread_mutex_lock@@GLIBC_2.2.5
                 w pthread_mutex_unlock@@GLIBC_2.2.5
                 w pthread_once
                 w pthread_setspecific
[root@d4a31a3e4d2c app]# nm -D /usr/lib64/libstdc++.so.6 | grep thread
000000000006a330 T _ZN9__gnu_cxx6__poolILb1EE16_M_get_thread_idEv@@GLIBCXX_3.4.4
000000000006a5b0 T _ZN9__gnu_cxx6__poolILb1EE21_M_destroy_thread_keyEPv@@GLIBCXX_3.4.4
00000000000b5170 T _ZNSt11this_thread11__sleep_forENSt6chrono8durationIlSt5ratioILl1ELl1EEEENS1_IlS2_ILl1ELl1000000000EEEE@@GLIBCXX_3.4.18
000000000007c410 T _ZNSt12__basic_fileIcEC1EP15pthread_mutex_t@@GLIBCXX_3.4
000000000007c410 T _ZNSt12__basic_fileIcEC2EP15pthread_mutex_t@@GLIBCXX_3.4
00000000000b53f0 T _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEE@@GLIBCXX_3.4.11
00000000000b5150 T _ZNSt6thread20hardware_concurrencyEv@@GLIBCXX_3.4.17
00000000000b50d0 T _ZNSt6thread4joinEv@@GLIBCXX_3.4.11
00000000000b5110 T _ZNSt6thread6detachEv@@GLIBCXX_3.4.11
000000000005ced0 T __cxa_thread_atexit@@CXXABI_1.3.7
                 w __pthread_key_create
                 w pthread_cond_broadcast@@GLIBC_2.3.2
                 w pthread_cond_destroy@@GLIBC_2.3.2
                 w pthread_cond_signal@@GLIBC_2.3.2
                 w pthread_cond_wait@@GLIBC_2.3.2
                 w pthread_create
                 w pthread_detach
                 w pthread_getspecific
                 w pthread_join
                 w pthread_key_create
                 w pthread_key_delete
                 w pthread_mutex_lock@@GLIBC_2.2.5
                 w pthread_mutex_unlock@@GLIBC_2.2.5
                 w pthread_once
                 w pthread_setspecific
```

There's no `_ZTINSt6thread6_StateE`

**Comment by henderkes** [comment]
craft.yml:

```yml
# PHP version to build (default: 8.4)
php-version: 8.4
# [REQUIRED] Static PHP extensions to build (list or comma-separated are both accepted)
extensions: apcu,ast,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,iconv,libxml,mbregex,mbstring,opcache,openssl,pcntl,phar,posix,readline,session,simplexml,sockets,sodium,tokenizer,xml,xmlreader,xmlwriter,zip,zlib
# [OPTIONAL] Shared PHP extensions to build (list or comma-separated are both accepted)
shared-extensions: [amqp,brotli,bz2,dio,ds,ev,event,ffi,ftp,gd,gettext,gmp,gmssl,igbinary,imagick,inotify,intl,ldap,lz4,memcache,memcached,mongodb,msgpack,mysqli,mysqlnd,odbc,opentelemetry,parallel,pdo,pdo_mysql,pdo_odbc,pdo_pgsql,pdo_sqlite,pdo_sqlsrv,pgsql,protobuf,rar,redis,rdkafka,shmop,spx,sqlite3,sqlsrv,ssh2,swoole,sysvmsg,sysvsem,sysvshm,tidy,uuid,uv,xdebug,xhprof,xlswriter,xsl,xz,yac,yaml,zstd]
# Extra libraries to build (list or comma-separated are both accepted)
libs: [libacl, libavif, nghttp3, ngtcp2, watcher]
# [REQUIRED] Build SAPIs (list or comma-separated are both accepted)
sapi: cli,embed,fpm
# Show full console output (default: false)
debug: false
# Build options (same as `build` command options, all options are optional)
build-options:
    # Build with Zend Thread Safety (ZTS) enabled (default: false)
    enable-zts: true
    # Before build, remove all old build files and sources (default: false)
    with-clean: false
    # Build with all suggested libraries (default: false)
    with-suggested-libs: true
    # Build with all suggested extensions (default: false)
    with-suggested-exts: false
    # Build without stripping the binary (default: false)
    no-strip: false
    # Disable Opcache JIT (default: false)
    disable-opcache-jit: false
    # PHP configuration options (same as --with-config-file-path)
    with-config-file-path: "/etc/php-zts.ini"
    # PHP configuration options (same as --with-config-file-scan-dir)
    with-config-file-scan-dir: "/etc/php-zts.d"
    # Hardcoded INI options for cli and micro SAPI (e.g. "memory_limit=4G", list accepted)
    with-hardcoded-ini: [ ]
    # Pretend micro SAPI as cli SAPI to avoid some frameworks to limit the usage of micro SAPI
    with-micro-fake-cli: false
    # Additional patch point injection files (e.g. "path/to/patch.php", list accepted)
    with-added-patch: [ ]
    # Ignore micro extension tests (if you are using micro SAPI, default: false)
    without-micro-ext-test: false
    # UPX pack the binary (default: false)
    with-upx-pack: false
    # Set the micro.exe program icon (only for Windows, default: "")
    with-micro-logo: ""
    # Set micro SAPI as win32 mode, without this, micro SAPI will be compiled as a console application (only for Windows, default: false)
    enable-micro-win32: false

# Download options
download-options:
    # Use custom url for specified sources, format: "{source-name}:{url}" (e.g. "php-src:https://example.com/php-8.4.0.tar.gz")
    custom-url: [ ]
    # Use custom git repo for specified sources, format: "{source-name}:{branch}:{url}" (e.g. "php-src:master:https://github.com/php/php-src.git")
    custom-git: [ ]
    # Retries count for downloading sources (default: 5)
    retry: 5
    # Use pre-built libraries if available (default: false)
    prefer-pre-built: false
    # Do not download from alternative sources (default: false)
    no-alt: false
    # Ignore cache sources, format: "{source-name}" (e.g. "php-src")
    ignore-cache-sources: 'php-src'

craft-options:
    doctor: true
    download: true
    build: true

# Extra environment variables
extra-env:
    # e.g. Use github token to avoid rate limit
    # GITHUB_TOKEN: your-github-token
    SPC_LIBC: glibc
    EXTENSION_DIR: /usr/lib64/php-zts/modules
    SPC_CMD_VAR_PHP_EMBED_TYPE: shared
    SPC_DEFAULT_C_FLAGS: "-fpic -O3 -fcf-protection -fstack-protector-strong -fstack-clash-protection"
    SPC_DEFAULT_CXX_FLAGS: "-fpic -O3 -fcf-protection -fstack-protector-strong -fstack-clash-protection"
    SPC_OPT_BUILD_ARGS: "--with-config-file-path=/etc/php-zts.ini --with-config-file-scan-dir=/etc/php-zts.d"
    SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS: "-g0 -fstack-protector-strong -O3 -fno-ident -fpic -fpie"
    SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS: "-pie -release zts-84"
    LDFLAGS: "-Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack"
    SPC_CMD_PREFIX_PHP_CONFIGURE: "./configure --prefix= --with-valgrind=no --disable-shared --enable-static --disable-all --disable-cgi --disable-phpdbg --disable-debug --with-pic --disable-dependency-tracking --enable-rtld-now"
    PHP_BUILD_PROVIDER: "Static PHP <https://static-php.dev> #StandWithUkraine"
    NO_CONFIGURE_COMMAND: true
```
